### ISSUE TITLE
แปลบทที่ 1 และ 2

### ISSUE THREAD

**Issue by PanJ** [reactbkk/react-in-patterns-th#2]
เริ่มจอง: 5 June 2018 18:00 ICT

**Comment by SimpleGet1975** [comment]
แย่งบัตรไม่ทัน งั้นขอจอง issue นี้นะ

**Comment by chayakornwc** [comment]
แย่งบัตรไม่ทัน งั้นขอจอง issue นี้นะ

**Comment by zenorp** [comment]
แย่งบัตรไม่ทัน งั้นขอจอง issue นี้นะ

**Comment by kykungz** [comment]
แย่งบัตรไม่ทัน งั้นขอจอง issue นี้นะ

**Comment by legendxr** [comment]
แย่งบัตรไม่ทัน งั้นขอจอง issue นี้นะ

**Comment by bazsup** [comment]
แย่งบัตรไม่ทัน งั้นขอจอง issue นี้นะ

**Comment by bazsup** [comment]
แย่งบัตรไม่ทัน งั้นขอจอง issue นี้นะ

**Comment by kcfinished** [comment]
แย่งบัตรไม่ทัน งั้นขอจอง issue นี้นะ

**Comment by bazsup** [comment]
แย่งบัตรไม่ทัน งั้นขอจอง issue นี้นะ

**Comment by chayakornwc** [comment]
แย่งบัตรไม่ทัน งั้นขอจอง issue นี้นะ

**Comment by kykungz** [comment]
แย่งบัตรไม่ทัน งั้นขอจอง issue นี้นะ

**Comment by kohpai** [comment]
แย่งบัตรไม่ทัน งั้นขอจอง issue นี้นะ

**Comment by kcfinished** [comment]
https://github.com/reactbkk/react-in-patterns-th/pull/18

**Comment by kcfinished** [comment]
ขอบคุณครับ

**Comment by pitsanujiw** [comment]
แย่งบัตรไม่ทัน งั้นขอจอง issue นี้นะ

**Comment by dtinth** [comment]
@pitsanujiw Issue #30 ยังว่างอยู่นะครับบ 😄

**Comment by dtinth** [comment]
@kcfinished ขอบคุณที่ Contribute นะครับ 😁

เข้าไปที่ https://reactbkk.com/3.0.0/#free-tickets แล้วล็อกอินด้วย GitHub Account เพื่อรับรหัสในการรับบัตรเข้างานฟรีได้เลยครับ

เนื่องจากทีมงานจะต้องสรุปยอดผู้เข้าร่วมงานภายในวันนี้ เพื่อจัดพิมพ์ป้ายชื่อ กรุณารับรหัส และเข้าไปกรอกรายละเอียดใน Event Pop ก่อนวันนี้ เวลา 18.00 ครับผม
