### ISSUE TITLE
เซ็ตอัพ storybook ให้โปรเจกต์ reactbkk/3.0.0

### ISSUE THREAD

**Issue by dtinth** [reactbkk/react-in-patterns-th#30]
เริ่มจอง วันพฤหัสที่ 7 มิถุนายน 2018, 17:00 น.

## Tasks

1. เซ็ตอัพ [storybook](https://storybook.js.org/) ใน[โปรเจกต์ reactbkk/3.0.0](https://github.com/reactbkk/3.0.0)

2. เอา UI ของ[หน้า `RedeemDialog`](https://github.com/reactbkk/3.0.0/blob/50b12087d983e72de410c0297d5d4ea6d006e2a6/src/redeem/RedeemDialog.js#L48:32) มาใส่ใน storybook โดยให้สามารถแสดงผล UI ของ state ต่อไปนี้:

   - initial: `{ status: 'initial' }`
   - error: `{ status: 'error', error: 'Error message' }`
   - signingIn: `{ status: 'signingIn' }`
   - checking: `{ status: 'checking' }`
   - checked (not found): `{ status: 'checked', code: '', admin: false }`
   - checked (found): `{ status: 'checked', code: 'ABCDEF', admin: false }`
   - checked (admin): `{ status: 'checked', code: 'ABCDEF', admin: true }`

   เนื่องจากตอนนี้่โค้ดที่เป็นส่วน logic ของหน้า `RedeemDialogContent` ยังปนอยู่กับโค้ดส่วนที่เป็น UI ให้แยกโค้ดสองส่วนนี้ออกจากกันก่อนครับ :D

**Comment by ohhox** [comment]
แย่งบัตรไม่ทัน งั้นขอจอง issue นี้นะ

**Comment by pitsanujiw** [comment]
แย่งบัตรไม่ทัน งั้นขอจอง issue นี้นะ

**Comment by monthol8th** [comment]
แย่งบัตรไม่ทัน งั้นขอจอง issue นี้นะ

**Comment by monthol8th** [comment]
แย่งบัตรไม่ทัน งั้นขอจอง issue นี้นะ

**Comment by monthol8th** [comment]
[](https://github.com/reactbkk/3.0.0/pull/16)

**Comment by monthol8th** [comment]
[https://github.com/reactbkk/3.0.0/pull/16]

**Comment by monthol8th** [comment]
https://github.com/reactbkk/3.0.0/pull/16

**Comment by dtinth** [comment]
@monthol8th ขอบคุณที่ Contribute ครับ 😃 

รับรหัสในการรับบัตรเข้างานฟรีได้ที่ https://reactbkk.com/3.0.0/#free-tickets โดยเมื่อล็อกอินผ่าน GitHub จะได้ Redemption code เอาไว้ใช้ Apply ใน Event Pop ครับ
